DROP TABLE IF EXISTS "NOTE";
DROP TABLE IF EXISTS "TICKET_FOR_SERVICE";
DROP TABLE IF EXISTS "TICKET";
DROP TABLE IF EXISTS "DOCTOR_SPECIALIZATION";
DROP TABLE IF EXISTS "DOCTOR_SERVICE";
DROP TABLE IF EXISTS "SPECIALIZATION";
DROP TABLE IF EXISTS "CLIENT";
DROP TABLE IF EXISTS "DOCTOR";
DROP TABLE IF EXISTS "SERVICE";

CREATE TABLE "SERVICE"
(
    "ID" INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(50) NOT NULL
);

CREATE TABLE "DOCTOR"
(
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    "LOGIN" VARCHAR(20) NOT NULL,
    "FIO" VARCHAR(50) NOT NULL,
    "BIRTHDATE" DATE NOT NULL,
    "PASSWORD" VARCHAR(200) NOT NULL,
    "SEX" VARCHAR(6) NOT NULL,
    PRIMARY KEY("ID", "LOGIN")
);

CREATE TABLE "CLIENT"
(
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    "SERTIFICATE" VARCHAR(20) NOT NULL,
    "FIO" VARCHAR(50) NOT NULL,
    "BIRTHDATE" DATE NOT NULL,
    "PASSWORD" VARCHAR(200) NOT NULL,
    "SEX" VARCHAR(6) NOT NULL,
    PRIMARY KEY("ID", "SERTIFICATE")
);

CREATE TABLE "SPECIALIZATION"
(
    "ID" INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(20) NOT NULL
);

CREATE TABLE "DOCTOR_SERVICE"
(
    "DOC_ID" INT NOT NULL,
    "SERVICE_ID" INT NOT NULL,
    "DOC_LOGIN" VARCHAR(20) NOT NULL,
    FOREIGN KEY ("DOC_ID", "DOC_LOGIN") REFERENCES "DOCTOR" ("ID", "LOGIN"),
    FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("ID"),
    PRIMARY KEY ("DOC_ID", "SERVICE_ID", "DOC_LOGIN")
);

CREATE TABLE "DOCTOR_SPECIALIZATION"
(
    "DOC_ID" INT NOT NULL,
    "SPECIALIZATION_ID" INT NOT NULL,
    "DOC_LOGIN" VARCHAR(20) NOT NULL,
    FOREIGN KEY ("DOC_ID", "DOC_LOGIN") REFERENCES "DOCTOR" ("ID", "LOGIN"),
    FOREIGN KEY ("SPECIALIZATION_ID") REFERENCES "SPECIALIZATION" ("ID"),
    PRIMARY KEY ("DOC_ID", "SPECIALIZATION_ID", "DOC_LOGIN")
);

CREATE TABLE "TICKET"
(
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    "DATE" DATE NOT NULL,
    "TIME" TIME WITH TIME ZONE NOT NULL,
    "PATIENT_SERTIFICATE" VARCHAR(20) NOT NULL,
    "CLIENT_ID" INT NOT NULL,
    "DOC_ID" INT NOT NULL,
    "DOC_LOGIN" VARCHAR(20) NOT NULL,
    FOREIGN KEY ("CLIENT_ID", "PATIENT_SERTIFICATE") REFERENCES "CLIENT" ("ID", "SERTIFICATE"),
    FOREIGN KEY ("DOC_ID", "DOC_LOGIN") REFERENCES "DOCTOR" ("ID", "LOGIN"),
    PRIMARY KEY ("ID")
);

CREATE TABLE "TICKET_FOR_SERVICE"
(
    "SERVICE_ID" INT NOT NULL,
    "TICKET_ID" INT NOT NULL,
    FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("ID"),
    FOREIGN KEY ("TICKET_ID") REFERENCES "TICKET" ("ID") ON DELETE CASCADE,
    PRIMARY KEY ("SERVICE_ID", "TICKET_ID")
);

CREATE TABLE "NOTE"
(
    "ID" INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    "DESCRIPTION" TEXT NOT NULL,
    "TICKET_ID" INT,
    "CLIENT_ID" INT NOT NULL,
    "PATIENT_SERTIFICATE" VARCHAR(20) NOT NULL,
    FOREIGN KEY ("TICKET_ID") REFERENCES "TICKET" ("ID"),
    FOREIGN KEY ("CLIENT_ID", "PATIENT_SERTIFICATE") REFERENCES "CLIENT" ("ID", "SERTIFICATE"),
    PRIMARY KEY ("ID")
);
