CREATE TABLE "TICKET_FOR_SERVICE"
(
    "SERVICE_ID" INT NOT NULL,
    "TICKET_ID" INT NOT NULL,
    FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("ID"),
    FOREIGN KEY ("TICKET_ID") REFERENCES "TICKET" ("ID") ON DELETE CASCADE,
    PRIMARY KEY ("SERVICE_ID", "TICKET_ID")
);